import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import SavedProfilesPanel from "@/components/SavedProfilesPanel";

export interface ManualProfile {
  name: string;
  email: string;
  phone: string;
  postcode: string;
  location: string;
  title: string;
  summary: string;
  experience: {
    company: string;
    startDate: string;
    endDate: string;
  }[];
  education: {
    degree: string;
    institution: string;
    year: string;
  }[];
  skills: string;
  certifications: string;
}

const emptyExperience = { company: "", startDate: "", endDate: "" };
const emptyEducation = { degree: "", institution: "", year: "" };

interface ManualEntryStepProps {
  profile: ManualProfile;
  onProfileChange: (profile: ManualProfile) => void;
  onNext: () => void;
  onBack: () => void;
}

const ManualEntryStep = ({ profile, onProfileChange, onNext, onBack }: ManualEntryStepProps) => {
  const update = (field: keyof ManualProfile, value: any) => {
    onProfileChange({ ...profile, [field]: value });
  };

  const updateExperience = (index: number, field: string, value: string) => {
    const updated = [...profile.experience];
    updated[index] = { ...updated[index], [field]: value };
    update("experience", updated);
  };

  const updateEducation = (index: number, field: string, value: string) => {
    const updated = [...profile.education];
    updated[index] = { ...updated[index], [field]: value };
    update("education", updated);
  };

  const isValid = profile.name.trim() && profile.email.trim();

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="max-w-2xl mx-auto"
    >
      <h2 className="font-heading text-3xl font-bold text-foreground mb-2 text-center">
        Enter Your Details
      </h2>
      <p className="text-muted-foreground text-center mb-8">
        Fill in your personal and professional information
      </p>

      <SavedProfilesPanel currentProfile={profile} onLoadProfile={onProfileChange} />

      <div className="space-y-6 bg-card rounded-xl p-6 md:p-8 shadow-card">
        <div>
          <h3 className="font-heading text-lg font-semibold text-foreground mb-4">
            Personal Information
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">Full Name *</Label>
              <Input id="name" placeholder="John Doe" value={profile.name} onChange={(e) => update("name", e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email *</Label>
              <Input id="email" type="email" placeholder="john@example.com" value={profile.email} onChange={(e) => update("email", e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">Phone</Label>
              <Input id="phone" placeholder="+44 7700 900000" value={profile.phone} onChange={(e) => update("phone", e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="postcode">Postcode</Label>
              <Input id="postcode" placeholder="SW1A 1AA" value={profile.postcode} onChange={(e) => update("postcode", e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label htmlFor="location">City / Location</Label>
              <Input id="location" placeholder="London, UK" value={profile.location} onChange={(e) => update("location", e.target.value)} />
            </div>
          </div>
          <p className="mt-4 text-sm text-muted-foreground italic">
            Professional title and summary will be generated by AI based on your job description.
          </p>
        </div>

        {/* Experience */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-heading text-lg font-semibold text-foreground">Experience</h3>
            <Button type="button" variant="outline" size="sm" onClick={() => update("experience", [...profile.experience, { ...emptyExperience }])}>
              <Plus className="w-4 h-4 mr-1" /> Add
            </Button>
          </div>
          <div className="space-y-4">
            {profile.experience.map((exp, i) => (
              <div key={i} className="border border-border rounded-lg p-4 relative">
                <button
                  type="button"
                  onClick={() => update("experience", profile.experience.filter((_, j) => j !== i))}
                  className="absolute top-3 right-3 p-1 text-muted-foreground hover:text-destructive transition-colors"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pr-8">
                  <Input placeholder="Company Name" value={exp.company} onChange={(e) => updateExperience(i, "company", e.target.value)} />
                  <Input placeholder="Start Date (e.g. Jan 2020)" value={exp.startDate} onChange={(e) => updateExperience(i, "startDate", e.target.value)} />
                  <Input placeholder="End Date (or Present)" value={exp.endDate} onChange={(e) => updateExperience(i, "endDate", e.target.value)} />
                </div>
              </div>
            ))}
            {profile.experience.length === 0 && (
              <p className="text-sm text-muted-foreground text-center py-4">No companies added yet</p>
            )}
          </div>
          <p className="text-sm text-muted-foreground italic mt-2">
            AI will generate roles, responsibilities, and skills based on the job description.
          </p>
        </div>

        {/* Education */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-heading text-lg font-semibold text-foreground">Education</h3>
            <Button type="button" variant="outline" size="sm" onClick={() => update("education", [...profile.education, { ...emptyEducation }])}>
              <Plus className="w-4 h-4 mr-1" /> Add
            </Button>
          </div>
          <div className="space-y-4">
            {profile.education.map((edu, i) => (
              <div key={i} className="border border-border rounded-lg p-4 relative">
                <button
                  type="button"
                  onClick={() => update("education", profile.education.filter((_, j) => j !== i))}
                  className="absolute top-3 right-3 p-1 text-muted-foreground hover:text-destructive transition-colors"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pr-8">
                  <Input placeholder="Degree" value={edu.degree} onChange={(e) => updateEducation(i, "degree", e.target.value)} />
                  <Input placeholder="Institution" value={edu.institution} onChange={(e) => updateEducation(i, "institution", e.target.value)} />
                  <Input placeholder="Year" value={edu.year} onChange={(e) => updateEducation(i, "year", e.target.value)} />
                </div>
              </div>
            ))}
            {profile.education.length === 0 && (
              <p className="text-sm text-muted-foreground text-center py-4">No education added yet</p>
            )}
          </div>
        </div>

        {/* Skills & Certs */}
        <div className="space-y-2">
          <Label htmlFor="certifications">Certifications (comma-separated)</Label>
          <Textarea id="certifications" placeholder="AWS Solutions Architect, PMP..." value={profile.certifications} onChange={(e) => update("certifications", e.target.value)} className="min-h-[80px] resize-none" />
        </div>
      </div>

      <div className="mt-8 flex justify-between">
        <Button variant="ghost" onClick={onBack}>
          Back
        </Button>
        <Button onClick={onNext} disabled={!isValid} size="lg">
          Continue
        </Button>
      </div>
    </motion.div>
  );
};

export default ManualEntryStep;
